name: amazon_iap
description: A flutter abstraction of the Amazon AppStore SDK.
version: 0.2.2
homepage: https://github.com/SongbookPro/flutter_amazon_iap

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^12.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.songbookpro.amazon_iap
        pluginClass: AmazonIapPlugin
